services:
  user-service:
    build:
      context: ./
      dockerfile: Presentation/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Key=${JWT_KEY}
      - MongoDb__ConnectionString=${MONGO_CONNECTION_STRING}
      - MongoDb__DatabaseName=${MONGO_DATABASE_NAME}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "password", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s